# samplenodeapp-ds-allnodes.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: samplenodeapp-ds
spec:
  template:
    metadata:
      labels:
        name: samplenodeapp
    spec:
      containers:
      - name: samplenodeapp
        image: gcr.io/gcp-wow-rwds-hwaravita-poc-dev/nodesample:v1
        ports:
            - containerPort: 3000
  selector:
    matchLabels:
      name: samplenodeapp