apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplenodeapp-deployment
  labels:
    app: samplenode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplenode
  template:
    metadata:
      labels:
        app: samplenode
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/gcp-wow-rwds-hwaravita-poc-dev/nodesample:v1
        ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: nodesample-service
spec:
    type: NodePort
    selector:
        app: samplenode
    ports:
        - protocol: TCP
          port: 3000
          nodePort: 30007